# Generated by Django 5.2 on 2025-04-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='PetsMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1)),
                ('birth', models.DateField()),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(choices=[('P', 'Pequeno'), ('PM', 'Pequeno/Médio'), ('M', 'Médio'), ('MG', 'Médio/Grande'), ('G', 'Grande')], default='P', max_length=2)),
                ('vacine', models.DateField(blank=True, null=True)),
                ('vermifuge', models.DateField(blank=True, null=True)),
                ('aptitude', models.CharField(choices=[('AP', 'Apto'), ('IN', 'Inapto'), ('PR', 'Em preparo')], default='AP', max_length=2)),
                ('front_photo', models.ImageField(upload_to='pets/photos/front/%y/%m/%d/')),
                ('side_photo', models.ImageField(blank=True, upload_to='pets/photos/side/%y/%m/%d/')),
                ('size_photo', models.ImageField(blank=True, upload_to='pets/photos/size/%y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.sector')),
            ],
        ),
    ]
