# Generated by Django 5.2 on 2025-04-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
    ]
