# Generated by Django 5.2 on 2025-04-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20250428_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sector',
            new_name='Setor',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='vacine',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='vermifuge',
        ),
    ]
