# Generated by Django 5.2 on 2025-04-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_sector_setor_remove_petsmod_vacine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsmod',
            name='vaccine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='vermifuge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
