# Generated by Django 5.2 on 2025-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_petsmod_vaccine_petsmod_vermifuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsmod',
            name='aptitude',
            field=models.CharField(choices=[('AP', 'Apto'), ('IN', 'Inapto'), ('PR', 'Em preparo'), ('AD', 'Adotado')], default='AP', max_length=2),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='side_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/side/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/size/%y/%m/%d/'),
        ),
    ]
