# Generated by Django 5.2 on 2025-04-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petsmod_aptitude_alter_petsmod_side_photo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setor',
            new_name='SectorMod',
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='size',
            field=models.CharField(choices=[('P', 'Pequeno'), ('PM', 'Peq/Médio'), ('M', 'Médio'), ('MG', 'Med/Grande'), ('G', 'Grande')], default='P', max_length=2),
        ),
    ]
