# Generated by Django 5.2 on 2025-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_rename_setor_sectormod_alter_petsmod_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectormod',
            name='tipo',
            field=models.CharField(choices=[('I', 'Individual'), ('C', 'Coletivo')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='sectormod',
            name='vaccine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectormod',
            name='vermifuge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
