# Generated by Django 5.2 on 2025-04-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_sectormod_tipo_sectormod_vaccine_sectormod_vermifuge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectormod',
            old_name='name',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='sectormod',
            old_name='tipo',
            new_name='type',
        ),
    ]
