# Generated by Django 5.2 on 2025-05-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_rename_name_sectormod_sector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectormod',
            old_name='sector',
            new_name='name',
        ),
    ]
