# Generated by Django 5.2.1 on 2025-05-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_rename_sector_sectormod_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectormod',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='sectormod',
            name='vermifuge',
        ),
    ]
